name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore Full-DAR-Redaction.sln
    - name: Check formatting
      run: dotnet format --no-restore --verify-no-changes
    - name: Build
      run: dotnet build Full-DAR-Redaction.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test Full-DAR-Redaction.sln --no-build --verbosity normal
